name:                warp-grpc
version:             0.1.0.4
github:              "lucasdicioccio/warp-grpc"
license:             BSD3
author:              "Lucas DiCioccio"
maintainer:          "lucas@dicioccio.fr"
copyright:           "2017 Lucas DiCioccio"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            A minimal gRPC server on top of Warp.
category:            Networking

description:         Please see the README on Github at <https://github.com/lucasdicioccio/warp-grpc#readme>

dependencies:
- base >= 4.11 && < 5
- async >= 2.2.1 && < 3
- binary >= 0.8.5 && < 0.9
- bytestring >= 0.10.8 && < 0.11
- case-insensitive >= 1.2.0 && < 1.3
- http2-grpc-types >= 0.3 && < 0.5
- http-types >= 0.12 && < 0.13
- proto-lens >= 0.3 && < 0.6
- wai >= 3.2 && < 3.3
- warp >= 3.2.24 && < 3.3
- warp-tls >= 3.2 && < 3.3
- proto3-wire >= 1 && < 1.1

library:
  source-dirs: src
